################################################################################
#	MODULE		:	Makefile
#	PROJECT		:	Cairo sample pdfgen
#	AUTHOR 		:	Michael Uman
#	DATE		:	April 17, 2013
################################################################################

TARGET_EXE=svggen
TARGET_TYPE=exe
CPP_SOURCES=svggen.cpp

include ../build/cairo_env.mk

CFLAGS+=$(CAIRO_CFLAGS)
LDFLAGS+=$(CAIRO_LIBS)

include ../build/buildsys.mk


# DO NOT DELETE
