################################################################################
#	MODULE		:	Makefile
#	PROJECT		:	Cairo sample toy-text
#	AUTHOR 		:	Michael Uman
#	DATE		:	April 17, 2013
################################################################################

TARGET_EXE=pango-list-typefaces
TARGET_TYPE=exe
C_SOURCES=pango-list-typefaces.c

include ../build/pango_env.mk

CFLAGS+=$(PANGO_CFLAGS)
LDFLAGS+=$(PANGO_LIBS)

include ../build/buildsys.mk


# DO NOT DELETE
