################################################################################
#	MODULE		:	Makefile
#	PROJECT		:	Cairo sample pdfgen
#	AUTHOR 		:	Michael Uman
#	DATE		:	April 17, 2013
################################################################################

TARGET_EXE=cairomm-surface
TARGET_TYPE=exe
CPP_SOURCES=cairomm-surface.cpp

include ../build/cairomm_env.mk

CFLAGS+=$(CAIROMM_CFLAGS)
LDFLAGS+=$(CAIROMM_LIBS)

include ../build/buildsys.mk


# DO NOT DELETE
